[Database]
user = "resonite-inventory"
password = "resonitepassword"
host = "db"
port = 3306
name = "resonite-inventory"

[Server]
<<<<<<< Updated upstream
host = "flintstones.asuscomm.com"
port =  5819
assetsPath = "./assets"
=======
host = "0.0.0.0"
port = 5819
assetsPath = "./assets"
>>>>>>> Stashed changes
